CREATE TABLE MEMBER (
    ID INT AUTO_INCREMENT NOT NULL,
    NAME VARCHAR2(50) NOT NULL,
    EMAIL VARCHAR2(100) NOT NULL,
    STREETADDRESS VARCHAR2(200) NOT NULL,
    CONTACTNO VARCHAR2(50) NOT NULL,
    BIOLOGY TEXT(4000),
    SUBURB VARCHAR2(50) NOT NULL,
    PRIMARY KEY (ID)
)