CREATE TABLE MEMBERSERVICE (
    ID INT AUTO_INCREMENT NOT NULL,
    MEMBERID INT NOT NULL,
    SERVICEID INT NOT NULL,
    CONSTRAINT FK_Member FOREIGN KEY (MEMBERID)
    REFERENCES MEMBER(ID),
    CONSTRAINT FK_Service FOREIGN KEY (SERVICEID)
    REFERENCES SERVICE(ID)
);